import '../globals.css'
import { Inter } from 'next/font/google'
import { getPages } from '../../sanity/sanity-utils'
import Navbar from './components/Navbar'
import Sidebar from './components/Sidebar'
import Link from 'next/link'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Mexico Tours',
  description: 'Generated by InfoArc.io',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pages = await getPages();
  return (
    <html lang="en">
      <body className="bg-black mx-auto max-w-6xl py-10">
        <header className="flex items-center justify-between">
          {/* <Link 
          href="/"
          className="mt-2 font-extrabold bg-gradient-to-r from-orange-500 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-extrabold">
          My Mexico Tours
          </Link>
          <nav className="mt-5">
            <ul className="flex space-x-5">
              {pages.map((page) => (
                <li key={page._id}>
                  <Link key={page._id} href={`/${page.slug}`} className="hover:underline">{page.title}</Link>
                </li>
              ))}
            </ul>
          </nav> */}
          <Navbar />
        </header>
        <main className="py-20">{children}</main>
        </body>
        <Footer />
    </html>
  )
}
